language: rust

rust:
  - stable
  - beta
  - nightly

services: memcache

before_script:
  - memcached -p 12345 -d
  - memcached -s /tmp/memcached.sock -d

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/memcache-*

script:
  - RUST_BACKTRACE=1 cargo test

notifications:
  email: false
