language: rust

rust:
  - stable
  - beta
  - nightly

services: memcache

before_script:
  - memcached -p 12345 -d
  - memcached -s /tmp/memcached.sock -d

script:
  - RUST_BACKTRACE=1 cargo test

notifications:
  email: false
