[package]
name = "memcache"
version = "0.9.2"
authors = ["asaka"]
repository = "https://github.com/aisk/rust-memcache"
readme = "README.md"
license = "MIT"
description = "memcached client for rust"
keywords = ["memcache", "memcached", "client", "driver", "cache", "database"]

[dependencies]
byteorder = "1"
url = "1"
rand = "0.3"
