[package]
name = "memcache"
version = "0.7.0"
authors = ["asaka"]
repository = "https://github.com/aisk/rust-memcache"
readme = "README.md"
license = "MIT"
description = "memcached client for rust"
keywords = ["memcache", "memcached", "client", "driver"]

[dependencies]
byteorder = "1"
url = "1"

[dev-dependencies]
rand = "0.3"
